[package]
name = "roc_desk_common"
version = "0.4.0"
edition = "2021"
license-file = "../../LICENSE"

[dependencies]
roc_desk_core = { path = "../core" }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "fs", "process"] }
encoding_rs = "0.8"
goblin = "0.9"
chrono = "0.4"
zip = { version = "2", default-features = false, features = ["deflate"] }
regex = "1"
